name: NameNotification
version: 1.3.0

main: me.richdev.NameNotification.Main
author: RichTheLord
description: A plugin that notificates you when a player send you a message in the chat.
softdepend: [DeluxeChat]
commands:
  namenotification:
    description: Main Command
    aliases: [nt, notification]